#######################
##  ObjectifRouting  ##
#######################

fi_thnitek_addObjectif:
  path:     /admin/addObjectif
  defaults: { _controller: FiThnitekBundle:Objectif:addObjectif }

fi_thnitek_listObjectif:
  path:     /admin/listObjectif
  defaults: { _controller: FiThnitekBundle:Objectif:listObjectif }

fi_thnitek_modifyObjectif:
  path:     /admin/modifyObjectif/{id}
  defaults: { _controller: FiThnitekBundle:Objectif:modifyObjectif }

fi_thnitek_deleteObjectif:
  path:     /admin/listObjectif/{id}
  defaults: { _controller: FiThnitekBundle:Objectif:deleteObjectif }

#######################
##  CategoryRouting  ##
#######################

fi_thnitek_addCategory:
  path:     /admin/addCategory
  defaults: { _controller: FiThnitekBundle:Category:addCategory }

fi_thnitek_listCategory:
  path:     /admin/listCategory
  defaults: { _controller: FiThnitekBundle:Category:listCategory }

fi_thnitek_modifyCategory:
  path:     /admin/modifyCategory/{id}
  defaults: { _controller: FiThnitekBundle:Category:modifyCategory }

fi_thnitek_deleteCategory:
  path:     /admin/listCategory/{id}
  defaults: { _controller: FiThnitekBundle:Category:deleteCategory }

##########################
##  LeaderBoardRouting  ##
##########################

fi_thnitek_addLeaderBoard:
  path:     /admin/addLeaderBoard
  defaults: { _controller: FiThnitekBundle:LeaderBoard:addLeaderBoard }

fi_thnitek_listLeaderBoard:
  path:     /admin/listLeaderBoard
  defaults: { _controller: FiThnitekBundle:LeaderBoard:listLeaderBoard }

fi_thnitek_modifyLeaderBoard:
  path:     /admin/modifyLeaderBoard/{id}
  defaults: { _controller: FiThnitekBundle:LeaderBoard:modifyLeaderBoard }

fi_thnitek_deleteLeaderBoard:
  path:     /admin/listLeaderBoard/{id}
  defaults: { _controller: FiThnitekBundle:LeaderBoard:deleteLeaderBoard }