fi_thnitek_homepage:
    path:     /
    defaults: { _controller: FiThnitekBundle:Default:index }
fi_thnitek_covoiturage:
    resource:    "@FiThnitekBundle/Resources/config/routingCovoiturage.yml"
    prefix: /covoiturage
fi_thnitek_homepageback:
    path:     /back
    defaults: { _controller: FiThnitekBundle:Default:indexback }