<?php

namespace FiThnitekBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function usernames()
    {
        $qb =$this->getEntityManager()
            ->createQuery("SELECT username FROM AppBundle:User");
        return $query=$qb->getResult();

    }
}
